# Generated by Django 4.1 on 2022-08-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_author_document_image_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
